import { useId, useRef, useState, type FormEvent } from 'react';
import { categories, universes, taxonomy, categoryLabels, universeLabels } from '../../../../shared/catalogTaxonomy.ts';
import { catalogChips } from '../hooks/catalogChips';
import type { CatalogQuery, Facets } from '../../../../shared/catalogQuery.ts';
type Props={query:CatalogQuery;facets?:Facets;total:number;change:(patch:Record<string,string|undefined>)=>void;reset:()=>void};

function Fields({query,facets,change}:Props){
 const group=useId();const [more,setMore]=useState(false);const count=(f:keyof Facets,s:string)=>facets?.[f][s]??0;
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);change({minPrice:String(f.get('min')??''),maxPrice:String(f.get('max')??'')});};
 return <div className="catalog-filter-fields">
 <details open><summary>Universo <span aria-hidden="true">⌄</span></summary><label><input type="radio" name={group+'universe'} checked={!query.universe} onChange={()=>change({universe:undefined})}/>Todos</label>{universes.map(s=><label key={s}><input type="radio" name="universe" checked={query.universe===s} onChange={()=>change({universe:s})}/>{universeLabels[s]} ({count('universe',s)})</label>)}</details>
 <details open><summary>Categoría <span aria-hidden="true">⌄</span></summary><label><input type="radio" name={group+'category'} checked={!query.category} onChange={()=>change({category:undefined})}/>Todos</label>{categories.map(s=><div key={s}><label><input type="radio" name="category" checked={query.category===s} onChange={()=>change({category:s})}/>{categoryLabels[s]} ({count('category',s)})</label>{query.category===s&&<div className="subcategory-list"><label><input type="radio" name={group+'subcategory'} checked={!query.subcategory} onChange={()=>change({subcategory:undefined})}/>Todos</label>{taxonomy[s].slice(0,more?undefined:6).map(i=><label key={i.slug}><input type="radio" name="subcategory" checked={query.subcategory===i.slug} onChange={()=>change({subcategory:i.slug})}/>{i.label} ({count('subcategory',i.slug)})</label>)}{taxonomy[s].length>6&&<button type="button" className="shop-link" onClick={()=>setMore(!more)}>{more?'Ver menos':'Ver más'}</button>}</div>}</div>)}</details>
 <details open><summary>Precio <span aria-hidden="true">⌄</span></summary><form key={String(query.minPrice)+'-'+query.maxPrice} onSubmit={submit}><label>Mínimo (MXN)<input name="min" className="shop-input" type="number" min="0" max="1000000" step="0.01" defaultValue={query.minPrice}/></label><label>Máximo (MXN)<input name="max" className="shop-input" type="number" min="0" max="1000000" step="0.01" defaultValue={query.maxPrice}/></label><button className="button-outline" type="submit">Aplicar</button></form><div className="price-ranges">{[[0,300],[300,600],[600,1000]].map(([min,max])=><button type="button" className="shop-link" key={min} onClick={()=>change({minPrice:String(min),maxPrice:String(max)})}>${min}–${max}</button>)}</div></details>
 <details open><summary>Ofertas <span aria-hidden="true">⌄</span></summary><label><input type="checkbox" checked={query.onSale===true} onChange={e=>change({onSale:e.target.checked?'true':undefined})}/>Solo ofertas</label></details></div>;
}
export function CatalogFilters(props:Props){
 const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);const [open,setOpen]=useState(false);const close=()=>dialog.current?.close();
 return <><aside className="catalog-sidebar" aria-label="Filtros del catálogo"><Fields {...props}/></aside><button ref={trigger} className="button-outline mobile-filter-trigger" type="button" aria-expanded={open} aria-controls="catalog-filter-dialog" onClick={()=>{dialog.current?.showModal();setOpen(true);}}>Filtros ({catalogChips(props.query).length})</button><dialog ref={dialog} id="catalog-filter-dialog" className="catalog-filter-drawer" aria-labelledby="catalog-filter-title" onCancel={e=>{e.preventDefault();close();}} onClose={()=>{setOpen(false);trigger.current?.focus();}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const nodes=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button,input,select,summary')).filter(n=>n.getClientRects().length>0);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><h2 id="catalog-filter-title">Filtrar catálogo</h2><button className="shop-link" type="button" onClick={close}>Cerrar filtros</button><Fields {...props}/><button className="shop-button" type="button" onClick={close}>Ver {props.total} resultados</button><button className="shop-link" type="button" onClick={props.reset}>Limpiar todo</button></dialog></>;
}